import { Achievement } from '@/types/achievements';

export const ACHIEVEMENTS: Achievement[] = [
  // ═══════════════════════════════════════════════════════════════
  // MILESTONE BADGES - Card count based
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'first-card',
    title: 'First Steps',
    description: 'Create your first wrapped card',
    icon: '🎯',
    gradient: 'magenta',
    category: 'milestone',
    rarity: 'common',
    criteria: { type: 'card_count', count: 1 },
    points: 10,
  },
  {
    id: 'getting-started',
    title: 'Getting Started',
    description: 'Create 5 wrapped cards',
    icon: '🌱',
    gradient: 'forest',
    category: 'milestone',
    rarity: 'common',
    criteria: { type: 'card_count', count: 5 },
    points: 25,
  },
  {
    id: 'double-digits',
    title: 'Double Digits',
    description: 'Create 10 wrapped cards',
    icon: '🔟',
    gradient: 'aurora',
    category: 'milestone',
    rarity: 'rare',
    criteria: { type: 'card_count', count: 10 },
    points: 50,
  },
  {
    id: 'quarter-century',
    title: 'Quarter Century',
    description: 'Create 25 wrapped cards',
    icon: '⚡',
    gradient: 'cosmic',
    category: 'milestone',
    rarity: 'epic',
    criteria: { type: 'card_count', count: 25 },
    points: 100,
  },
  {
    id: 'completionist',
    title: 'Completionist',
    description: 'Create all 46 wrapped cards',
    icon: '👑',
    gradient: 'golden',
    category: 'milestone',
    rarity: 'legendary',
    criteria: { type: 'all_categories_complete' },
    points: 500,
  },

  // ═══════════════════════════════════════════════════════════════
  // CATEGORY COMPLETION BADGES
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'people-master',
    title: 'People Person',
    description: 'Complete all People Who Shaped Your Year subcategories',
    icon: '🏆',
    gradient: 'magenta',
    category: 'category',
    rarity: 'epic',
    criteria: { type: 'category_complete', mainCategoryId: 'people' },
    points: 75,
  },
  {
    id: 'family-master',
    title: 'Family First',
    description: 'Complete all Family & Home subcategories',
    icon: '👨‍👩‍👧‍👦',
    gradient: 'golden',
    category: 'category',
    rarity: 'legendary',
    criteria: { type: 'category_complete', mainCategoryId: 'family' },
    points: 120,
  },
  {
    id: 'friendships-master',
    title: 'Social Butterfly',
    description: 'Complete all Friendships & Community subcategories',
    icon: '👯‍♂️',
    gradient: 'aurora',
    category: 'category',
    rarity: 'legendary',
    criteria: { type: 'category_complete', mainCategoryId: 'friendships' },
    points: 150,
  },
  {
    id: 'entertainment-master',
    title: 'Culture Vulture',
    description: 'Complete all Entertainment subcategories',
    icon: '🎬',
    gradient: 'cosmic',
    category: 'category',
    rarity: 'epic',
    criteria: { type: 'category_complete', mainCategoryId: 'entertainment' },
    points: 85,
  },
  {
    id: 'food-master',
    title: 'Foodie',
    description: 'Complete all Food & Dining subcategories',
    icon: '🍕',
    gradient: 'sunset',
    category: 'category',
    rarity: 'rare',
    criteria: { type: 'category_complete', mainCategoryId: 'food' },
    points: 60,
  },
  {
    id: 'lifestyle-master',
    title: 'Lifestyle Guru',
    description: 'Complete all Lifestyle subcategories',
    icon: '✨',
    gradient: 'aurora',
    category: 'category',
    rarity: 'rare',
    criteria: { type: 'category_complete', mainCategoryId: 'lifestyle' },
    points: 50,
  },
  {
    id: 'habits-master',
    title: 'Wellness Warrior',
    description: 'Complete all Habits & Wellness subcategories',
    icon: '💪',
    gradient: 'forest',
    category: 'category',
    rarity: 'rare',
    criteria: { type: 'category_complete', mainCategoryId: 'habits' },
    points: 50,
  },
  {
    id: 'achievements-master',
    title: 'Overachiever',
    description: 'Complete all Achievements subcategories',
    icon: '🏆',
    gradient: 'golden',
    category: 'category',
    rarity: 'epic',
    criteria: { type: 'category_complete', mainCategoryId: 'achievements' },
    points: 60,
  },
  {
    id: 'travel-master',
    title: 'Globetrotter',
    description: 'Complete all Travel subcategories',
    icon: '✈️',
    gradient: 'ocean',
    category: 'category',
    rarity: 'rare',
    criteria: { type: 'category_complete', mainCategoryId: 'travel' },
    points: 50,
  },
  {
    id: 'relationships-master',
    title: 'Heart of Gold',
    description: 'Complete all Relationships subcategories',
    icon: '💕',
    gradient: 'berry',
    category: 'category',
    rarity: 'rare',
    criteria: { type: 'category_complete', mainCategoryId: 'relationships' },
    points: 40,
  },
  {
    id: 'education-master',
    title: 'Scholar',
    description: 'Complete all Education subcategories',
    icon: '🎓',
    gradient: 'midnight',
    category: 'category',
    rarity: 'rare',
    criteria: { type: 'category_complete', mainCategoryId: 'education' },
    points: 40,
  },
  {
    id: 'misc-master',
    title: 'Wild Card',
    description: 'Complete all Miscellaneous subcategories',
    icon: '🎲',
    gradient: 'fire',
    category: 'category',
    rarity: 'rare',
    criteria: { type: 'category_complete', mainCategoryId: 'miscellaneous' },
    points: 50,
  },
  {
    id: 'faith-master',
    title: 'Kingdom Builder',
    description: 'Complete all Faith & Spiritual Life subcategories',
    icon: '🙏',
    gradient: 'golden',
    category: 'category',
    rarity: 'legendary',
    criteria: { type: 'category_complete', mainCategoryId: 'faith' },
    points: 150,
  },
  {
    id: 'connections-master',
    title: 'Love Expert',
    description: 'Complete all Relationships & Connections subcategories',
    icon: '💑',
    gradient: 'berry',
    category: 'category',
    rarity: 'legendary',
    criteria: { type: 'category_complete', mainCategoryId: 'connections' },
    points: 140,
  },
  {
    id: 'career-master',
    title: 'Career Champion',
    description: 'Complete all Career, Work & Stewardship subcategories',
    icon: '💼',
    gradient: 'midnight',
    category: 'category',
    rarity: 'legendary',
    criteria: { type: 'category_complete', mainCategoryId: 'career' },
    points: 160,
  },
  {
    id: 'finance-master',
    title: 'Money Master',
    description: 'Complete all Money & Financial Discipline subcategories',
    icon: '💸',
    gradient: 'golden',
    category: 'category',
    rarity: 'epic',
    criteria: { type: 'category_complete', mainCategoryId: 'finance' },
    points: 100,
  },
  {
    id: 'naija-food-master',
    title: 'Foodie Supreme',
    description: 'Complete all Food & Daily Life subcategories',
    icon: '🍲',
    gradient: 'sunset',
    category: 'category',
    rarity: 'legendary',
    criteria: { type: 'category_complete', mainCategoryId: 'naija-food' },
    points: 150,
  },
  {
    id: 'naija-entertainment-master',
    title: 'Entertainment Connoisseur',
    description: 'Complete all Music, Media & Entertainment subcategories',
    icon: '🎶',
    gradient: 'magenta',
    category: 'category',
    rarity: 'legendary',
    criteria: { type: 'category_complete', mainCategoryId: 'naija-entertainment' },
    points: 200,
  },
  {
    id: 'style-master',
    title: 'Style Icon',
    description: 'Complete all Style & Presentation subcategories',
    icon: '👗',
    gradient: 'magenta',
    category: 'category',
    rarity: 'epic',
    criteria: { type: 'category_complete', mainCategoryId: 'style' },
    points: 120,
  },
  {
    id: 'digital-master',
    title: 'Digital Native',
    description: 'Complete all Digital Life & Online Presence subcategories',
    icon: '📱',
    gradient: 'cosmic',
    category: 'category',
    rarity: 'legendary',
    criteria: { type: 'category_complete', mainCategoryId: 'digital' },
    points: 140,
  },
  {
    id: 'naija-travel-master',
    title: 'Explorer',
    description: 'Complete all Travel & Movement subcategories',
    icon: '✈️',
    gradient: 'ocean',
    category: 'category',
    rarity: 'epic',
    criteria: { type: 'category_complete', mainCategoryId: 'naija-travel' },
    points: 130,
  },
  {
    id: 'learning-growth-master',
    title: 'Lifelong Learner',
    description: 'Complete all Learning & Growth subcategories',
    icon: '🎓',
    gradient: 'forest',
    category: 'category',
    rarity: 'legendary',
    criteria: { type: 'category_complete', mainCategoryId: 'learning-growth' },
    points: 140,
  },
  {
    id: 'health-wellbeing-master',
    title: 'Wellness Champion',
    description: 'Complete all Health & Wellbeing subcategories',
    icon: '💪',
    gradient: 'forest',
    category: 'category',
    rarity: 'legendary',
    criteria: { type: 'category_complete', mainCategoryId: 'health-wellbeing' },
    points: 150,
  },
  {
    id: 'memorable-moments-master',
    title: 'Memory Keeper',
    description: 'Complete all Memorable Moments subcategories',
    icon: '🎉',
    gradient: 'magenta',
    category: 'category',
    rarity: 'legendary',
    criteria: { type: 'category_complete', mainCategoryId: 'memorable-moments' },
    points: 180,
  },
  {
    id: 'achievements-wins-master',
    title: 'Victor',
    description: 'Complete all Achievements & Wins subcategories',
    icon: '🏆',
    gradient: 'golden',
    category: 'category',
    rarity: 'legendary',
    criteria: { type: 'category_complete', mainCategoryId: 'achievements-wins' },
    points: 150,
  },
  {
    id: 'hobbies-interests-master',
    title: 'Renaissance Soul',
    description: 'Complete all Hobbies & Interests subcategories',
    icon: '🎮',
    gradient: 'berry',
    category: 'category',
    rarity: 'epic',
    criteria: { type: 'category_complete', mainCategoryId: 'hobbies-interests' },
    points: 120,
  },
  {
    id: 'naija-culture-master',
    title: 'Naija Ambassador',
    description: 'Complete all Nigerian Culture & Reality subcategories',
    icon: '🇳🇬',
    gradient: 'forest',
    category: 'category',
    rarity: 'legendary',
    criteria: { type: 'category_complete', mainCategoryId: 'naija-culture' },
    points: 200,
  },
  {
    id: 'personal-reflection-master',
    title: 'Deep Thinker',
    description: 'Complete all Personal Reflection subcategories',
    icon: '💭',
    gradient: 'aurora',
    category: 'category',
    rarity: 'epic',
    criteria: { type: 'category_complete', mainCategoryId: 'personal-reflection' },
    points: 120,
  },
  {
    id: 'wild-cards-master',
    title: 'Wild Child',
    description: 'Complete all Wild Cards subcategories',
    icon: '🎲',
    gradient: 'fire',
    category: 'category',
    rarity: 'legendary',
    criteria: { type: 'category_complete', mainCategoryId: 'wild-cards' },
    points: 160,
  },
  {
    id: 'quick-stats-master',
    title: 'Data Enthusiast',
    description: 'Complete all Quick Stats subcategories',
    icon: '📊',
    gradient: 'cosmic',
    category: 'category',
    rarity: 'epic',
    criteria: { type: 'category_complete', mainCategoryId: 'quick-stats' },
    points: 100,
  },
  {
    id: 'year-close-master',
    title: 'Year Closer',
    description: 'Complete all End-of-Year Close subcategories',
    icon: '💫',
    gradient: 'golden',
    category: 'category',
    rarity: 'legendary',
    criteria: { type: 'category_complete', mainCategoryId: 'year-close' },
    points: 150,
  },

  // ═══════════════════════════════════════════════════════════════
  // SPECIAL COMBOS & THEMED ACHIEVEMENTS
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'music-lover',
    title: 'Music Lover',
    description: 'Complete Song of the Year and Best Concert',
    icon: '🎵',
    gradient: 'magenta',
    category: 'combo',
    rarity: 'rare',
    criteria: {
      type: 'subcategories_complete',
      subcategoryIds: ['favorite-song', 'top-concert'],
    },
    points: 35,
  },
  {
    id: 'bookworm',
    title: 'Bookworm',
    description: 'Complete Book of the Year and Course Completed',
    icon: '📚',
    gradient: 'forest',
    category: 'combo',
    rarity: 'rare',
    criteria: {
      type: 'subcategories_complete',
      subcategoryIds: ['top-book', 'course-completed'],
    },
    points: 35,
  },
  {
    id: 'adventurer',
    title: 'Adventurer',
    description: 'Complete Best Trip, Bucket List Check, and Road Trip',
    icon: '🗺️',
    gradient: 'ocean',
    category: 'combo',
    rarity: 'epic',
    criteria: {
      type: 'subcategories_complete',
      subcategoryIds: ['best-trip', 'bucket-list', 'road-trip'],
    },
    points: 55,
  },
  {
    id: 'inner-circle',
    title: 'Inner Circle',
    description: 'Complete Friend of the Year, Top 5 Friends, and Best New Connection',
    icon: '💜',
    gradient: 'cosmic',
    category: 'combo',
    rarity: 'epic',
    criteria: {
      type: 'subcategories_complete',
      subcategoryIds: ['friend-of-year', 'top-5-friends', 'best-new-connection'],
    },
    points: 55,
  },
  {
    id: 'self-care-king',
    title: 'Self-Care Champion',
    description: 'Complete Self-Care Moment, Mindfulness Journey, and Sleep Stats',
    icon: '🧘',
    gradient: 'aurora',
    category: 'combo',
    rarity: 'rare',
    criteria: {
      type: 'subcategories_complete',
      subcategoryIds: ['self-care-moment', 'mindfulness', 'sleep-stats'],
    },
    points: 45,
  },
  {
    id: 'goal-getter',
    title: 'Goal Getter',
    description: 'Complete Biggest Win, Goal Achieved, and Personal Award',
    icon: '🎯',
    gradient: 'golden',
    category: 'combo',
    rarity: 'epic',
    criteria: {
      type: 'subcategories_complete',
      subcategoryIds: ['biggest-win', 'goal-achieved', 'personal-award'],
    },
    points: 55,
  },
  {
    id: 'family-bonds',
    title: 'Family Bonds',
    description: 'Complete Family MVP, Family Gathering, and Elder Wisdom',
    icon: '💝',
    gradient: 'sunset',
    category: 'combo',
    rarity: 'epic',
    criteria: {
      type: 'subcategories_complete',
      subcategoryIds: ['family-mvp', 'family-gathering', 'elder-wisdom'],
    },
    points: 50,
  },
  {
    id: 'gamer',
    title: 'Gamer',
    description: 'Complete Game of the Year',
    icon: '🎮',
    gradient: 'berry',
    category: 'combo',
    rarity: 'common',
    criteria: {
      type: 'subcategories_complete',
      subcategoryIds: ['top-game'],
    },
    points: 15,
  },
  {
    id: 'fitness-freak',
    title: 'Fitness Freak',
    description: 'Complete Top Habits and Fitness Stats',
    icon: '🏋️',
    gradient: 'fire',
    category: 'combo',
    rarity: 'rare',
    criteria: {
      type: 'subcategories_complete',
      subcategoryIds: ['top-habits', 'fitness-stats'],
    },
    points: 35,
  },

  // ═══════════════════════════════════════════════════════════════
  // SPECIAL / HIDDEN ACHIEVEMENTS
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'night-owl',
    title: 'Night Owl',
    description: 'Create a card after midnight',
    icon: '🦉',
    gradient: 'midnight',
    category: 'special',
    rarity: 'rare',
    criteria: { type: 'custom', checkId: 'night-owl' },
    points: 25,
    hidden: true,
  },
  {
    id: 'early-bird',
    title: 'Early Bird',
    description: 'Create a card before 6 AM',
    icon: '🐦',
    gradient: 'sunset',
    category: 'special',
    rarity: 'rare',
    criteria: { type: 'custom', checkId: 'early-bird' },
    points: 25,
    hidden: true,
  },
  {
    id: 'perfectionist',
    title: 'Perfectionist',
    description: 'Fill in every field on a card including optional ones',
    icon: '✅',
    gradient: 'aurora',
    category: 'special',
    rarity: 'rare',
    criteria: { type: 'custom', checkId: 'perfectionist' },
    points: 30,
    hidden: true,
  },
];

export const getAchievementById = (id: string): Achievement | undefined => {
  return ACHIEVEMENTS.find((a) => a.id === id);
};

export const getAchievementsByCategory = (
  category: Achievement['category']
): Achievement[] => {
  return ACHIEVEMENTS.filter((a) => a.category === category);
};

export const TOTAL_POSSIBLE_POINTS = ACHIEVEMENTS.reduce(
  (sum, a) => sum + a.points,
  0
);
